spring.application.name=phudaosof3062

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=PhuDaoSOF3062SP26B2;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123456
spring.jpa.show-sql=true